/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "../../riped/useGLTF";

export default function CardWorld({ ...props }) {
  const group = useRef(null!);
  // @ts-ignore
  const { nodes, materials } = useGLTF("/assets/cards_world.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.world_cards.geometry}
        material={materials.palette}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/assets/cards_world.gltf", true, true, undefined);
